"""MCP tool implementations and dispatch table."""

from __future__ import annotations

import asyncio
import logging
import math
import re
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional, TYPE_CHECKING

from ._shared import (
    DICTIONARY_PATHS,
    PATHWAY_CAP,
    RRF_K,
    VALENCE_WEIGHT,
    _CONCEPT_INDEX,
    _CONCEPT_TABLE,
    _LESSON_INDEX,
    _LESSON_TABLE,
    _PLAN_INDEX,
    _PLAN_TABLE,
    _PROCEDURE_INDEX,
    _PROCEDURE_TABLE,
    _apply_fusion_adjustments,
    _clamp,
    _get_pk_for_node_type,
    _logger,
    _normalize_steps,
    _rrf_fuse,
    _safe_result_dict,
    _session_active_plan_id,
    _with_phase,
    emb,
    detect_ordered_plan_steps,
    find_dictionary,
    get_or_create_main_quest,
    get_or_create_session,
    get_quest_context,
    get_table,
    has_plan_signal,
    ingest_dictionary,
    infer_outcome_valence,
    init_loop_queue,
    load_dictionary,
    pk_for,
    tables_with,
    create_side_quest,
)
from .arc_tools import (
    arc_check_action_gate,
    arc_classify_game_archetype,
    arc_confirm_hypothesis,
    arc_contradict_hypothesis,
    arc_get_action_evidence,
    arc_get_causal_path,
    get_entity_history,
    arc_get_entity_movement,
    arc_get_entity_neighborhood,
    arc_get_game_context,
    arc_get_goal_evidence,
    arc_get_mechanic_priors,
    get_rules_for_action,
    get_transferred_rules,
    arc_get_untested_actions,
    arc_perceive_state,
    arc_record_action_effect,
    arc_record_reward_prediction_error,
    record_rule,
    record_transition,
    arc_update_goal_confidence,
    ingest_arc_artifacts,
    publish_mechanic_summary,
    recall_mechanic_priors,
)
from .artifacts import _ARTIFACT_TYPE_MAP, _infer_document_type, register_artifact
from .capture import _maybe_create_passive_plan_from_turn, notify_turn
from .context_tools import ask, compile_card_context, compile_context, ingest_data, ingest_document, memory_decision
from .lessons import (
    _create_plan_graph,
    _plan_feedback_from_similarity,
    _store_plan_outcome_lesson,
    _synthesize_lesson,
    recall_relevant_lessons,
    recall_scene_graph_priors,
    upsert_lesson,
)
from .quests import (
    advance_task,
    branch_quest,
    complete_quest,
    fail_task,
    get_anomalies,
    get_disambiguation_queue,
    get_openclaw_prompt,
    get_ready_tasks,
    get_task_graph,
    recall_plans,
    recall_procedures,
    register_plan,
    register_task_graph,
    report_outcome,
    resolve_disambiguation,
    set_quest,
)
from .retrieval import (
    _MAX_DEPTH,
    _NODE_TABLES,
    _TRAVERSABLE_RELS,
    analogical_search,
    context_status,
    current_truth,
    diff_since,
    explore_graph,
    get_knowledge_gaps,
    get_open_loops,
    reconstruct_timeline,
    reload_domain_dictionary,
)

TOOL_HANDLERS = {
    # Encoding phase (write path)
    "notify_turn":      _with_phase("encoding", notify_turn),
    "ingest_document":  _with_phase("encoding", ingest_document),
    "ingest_data":      _with_phase("encoding", ingest_data),
    "upsert_lesson":    _with_phase("encoding", upsert_lesson),
    "register_artifact": _with_phase("encoding", register_artifact),

    # Recalling phase (read path)
    "current_truth":    _with_phase("recalling", current_truth),
    "compile_context":  _with_phase("recalling", compile_context),
    "compile_card_context": _with_phase("recalling", compile_card_context),
    "ask":              _with_phase("recalling", ask),
    "recall_relevant_lessons": _with_phase("recalling", recall_relevant_lessons),
    "recall_procedures": _with_phase("recalling", recall_procedures),
    "recall_plans":    _with_phase("recalling", recall_plans),
    "reconstruct_timeline": _with_phase("recalling", reconstruct_timeline),
    "analogical_search": _with_phase("recalling", analogical_search),
    "explore_graph":    _with_phase("recalling", explore_graph),
    "memory_decision": _with_phase("recalling", memory_decision),

    # Lightweight metadata ops (no phase wrapping)
    "branch_quest":     branch_quest,
    "complete_quest":   complete_quest,
    "diff_since":       diff_since,
    "get_open_loops":   get_open_loops,
    "set_quest":        set_quest,
    "context_status":   context_status,
    "get_anomalies":    get_anomalies,
    "recall_scene_graph_priors": recall_scene_graph_priors,
    "get_openclaw_prompt": get_openclaw_prompt,
    "register_plan":   register_plan,
    "report_outcome":  report_outcome,
    "get_knowledge_gaps": get_knowledge_gaps,
    "register_task_graph": register_task_graph,
    "get_ready_tasks":     get_ready_tasks,
    "advance_task":        advance_task,
    "fail_task":           fail_task,
    "get_task_graph":      get_task_graph,
    "get_disambiguation_queue": get_disambiguation_queue,
    "resolve_disambiguation": resolve_disambiguation,
    "reload_domain_dictionary": reload_domain_dictionary,
    "ingest_arc_artifacts": ingest_arc_artifacts,
    "publish_mechanic_summary": publish_mechanic_summary,
    "recall_mechanic_priors": recall_mechanic_priors,
    "arc_perceive_state": arc_perceive_state,
    "arc_get_game_context": arc_get_game_context,
    "arc_get_action_evidence": arc_get_action_evidence,
    "arc_get_untested_actions": arc_get_untested_actions,
    "arc_get_causal_path": arc_get_causal_path,
    "arc_record_action_effect": arc_record_action_effect,
    "arc_get_entity_movement": arc_get_entity_movement,
    "arc_get_entity_neighborhood": arc_get_entity_neighborhood,
    "arc_get_goal_evidence": arc_get_goal_evidence,
    "arc_classify_game_archetype": arc_classify_game_archetype,
    "arc_confirm_hypothesis": arc_confirm_hypothesis,
    "arc_contradict_hypothesis": arc_contradict_hypothesis,
    "arc_update_goal_confidence": arc_update_goal_confidence,
    "arc_get_mechanic_priors": arc_get_mechanic_priors,
    "arc_check_action_gate": arc_check_action_gate,
    "arc_record_reward_prediction_error": arc_record_reward_prediction_error,
    # B309 — A175-A179 pending server-side half; do NOT wrap with
    # _with_phase(), matching B278's existing ARC tools above.
    "record_transition": record_transition,
    "get_entity_history": get_entity_history,
    "record_rule": record_rule,
    "get_rules_for_action": get_rules_for_action,
    "get_transferred_rules": get_transferred_rules,
}
