"""Product naming constants and legacy compatibility aliases."""

PRODUCT_NAME = "HippoCampy"
SHORT_NAME = "Campy"
PRIMARY_CLI = "campy"
LEGACY_CLI = "sidequests"
PRIMARY_MCP_SERVER = "campy"
LEGACY_MCP_SERVER = "sidequests"
PRIMARY_DISTRIBUTION = "hippocampy"
LEGACY_DISTRIBUTION = "sidequests-brain"
PRIMARY_RUNTIME_DIR = ".campy"
LEGACY_RUNTIME_DIR = ".sidequests"
PRIMARY_LAUNCHD_LABEL = "ai.hippocampy.brain"
LEGACY_LAUNCHD_LABEL = "ai.sidequests.brain"
LEGACY_LAUNCHD_LABELS = ("ai.sidequests.brain", "ai.campy.brain")
PRIMARY_SKILL_NAME = "campy-memory"
LEGACY_SKILL_NAME = "sidequests-memory"
